<?php

declare(strict_types=1);

use Drupal\Core\Access\AccessResultInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_entity_type_alter().
 */
function tengstrom_emails_entity_type_alter(array &$entityTypes) {
  /** @var \Drupal\tengstrom_emails\HookHandlers\EntityTypeAlterHandler $service */
  $service = \Drupal::service('tengstrom_emails.hook_handlers.entity_type_alter');

  $service->alter($entityTypes);
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function tengstrom_emails_easy_email_type_access(EntityInterface $entity, string $operation, AccountInterface $account): AccessResultInterface {
  /** @var \Drupal\tengstrom_emails\HookHandlers\EasyEmailTypeAccessHandler $service */
  $service = \Drupal::service('tengstrom_emails.hook_handlers.easy_email_type_access_handler');

  return $service->checkAccess($entity, $operation, $account);
}

/**
 * Implements hook_ENTITY_TYPE_create_access().
 */
function tengstrom_emails_easy_email_type_create_access(AccountInterface $account, array $context, ?string $entityBundle): AccessResultInterface {
  /** @var \Drupal\tengstrom_emails\HookHandlers\EasyEmailTypeAccessHandler $service */
  $service = \Drupal::service('tengstrom_emails.hook_handlers.easy_email_type_access_handler');

  return $service->checkCreateAccess($account, $context, $entityBundle);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function tengstrom_emails_form_easy_email_type_edit_form_alter(array &$form, FormStateInterface $formState, string $formId) {
  /** @var \Drupal\tengstrom_emails\HookHandlers\FormAlterHandlers\EasyEmailTypeEditFormAlterHandler $service */
  $service = \Drupal::service('tengstrom_emails.hook_handlers.easy_email_type_edit_form_alter');

  $service->alter($form, $formState, $formId);
}

/**
 * Implements template_preprocess_email_wrap().
 */
function tengstrom_emails_preprocess_email_wrap(array &$variables) {
  /** @var \Drupal\tengstrom_emails\HookHandlers\PreprocessHandlers\PreprocessEmailWrapHandler $service */
  $service = \Drupal::service('tengstrom_emails.hook_handlers.preprocess_email_wrap');

  $service->preprocess($variables);
}
